// <auto-generated />
using Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Contexto.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20180406024027_PreguntaDeSeguridad")]
    partial class PreguntaDeSeguridad
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Modelo.Capitulo", b =>
                {
                    b.Property<int>("CapituloID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DireccionDelCapitulo")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("NombreDelCapitulo")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<int>("NumeroCapitulo");

                    b.Property<int>("SerieId");

                    b.Property<string>("Temporada")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("CapituloID");

                    b.HasIndex("SerieId");

                    b.ToTable("Capitulo");
                });

            modelBuilder.Entity("Modelo.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Generos")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("GeneroId");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("Modelo.GeneroSerie", b =>
                {
                    b.Property<int>("GeneroSerieId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GeneroId");

                    b.Property<int>("SerieId");

                    b.HasKey("GeneroSerieId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("SerieId");

                    b.ToTable("GeneroSerie");
                });

            modelBuilder.Entity("Modelo.Serie", b =>
                {
                    b.Property<int>("SerieId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Anio")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Productora")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Temporadas")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.HasKey("SerieId");

                    b.ToTable("Serie");
                });

            modelBuilder.Entity("Modelo.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("NombreCuenta")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("PreguntaDeSeguridad")
                        .HasMaxLength(30);

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Modelo.UsuarioSerie", b =>
                {
                    b.Property<int>("UsuarioSerieId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SerieId");

                    b.Property<int>("UsuarioId");

                    b.HasKey("UsuarioSerieId");

                    b.HasIndex("SerieId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioSerie");
                });

            modelBuilder.Entity("Modelo.Capitulo", b =>
                {
                    b.HasOne("Modelo.Serie", "Serie")
                        .WithMany("Capitulos")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Modelo.GeneroSerie", b =>
                {
                    b.HasOne("Modelo.Genero", "Genero")
                        .WithMany("Series")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Modelo.Serie", "Serie")
                        .WithMany("Generos")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Modelo.UsuarioSerie", b =>
                {
                    b.HasOne("Modelo.Serie", "Serie")
                        .WithMany("Usuarios")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Modelo.Usuario", "Usuario")
                        .WithMany("Series")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
