// <auto-generated />
using Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Contexto.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20180301234008_AgregandoFileALaImagen")]
    partial class AgregandoFileALaImagen
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Modelo.Pelicula", b =>
                {
                    b.Property<int>("PeliculaId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Anio");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PeliculaCompleta")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Productora")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("PeliculaId");

                    b.ToTable("Pelicula");
                });

            modelBuilder.Entity("Modelo.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("NombreCuenta")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
